//
//  Currency.swift
//  Finply
//
//  Created by Illia Postoienko on 24.12.2020.
//

// swiftlint:disable type_body_length
enum Currency: String, CaseIterable {
    
    case albaniaLek = "ALL"
    case afghani = "AFN"
    case algerianDinar = "DZD"
    case argentinePeso = "ARS"
    case armenianDram = "AMD"
    case arubanFlorin = "AWG"
    case australianDollar = "AUD"
    case azerbaijanManat = "AZN"
    case bahamianDollar = "BSD"
    case bahrainiDinar = "BHD"
    case baht = "THB"
    case balboa = "PAB"
    case barbadosDollar = "BBD"
    case belarusianRuble = "BYN"
    case belizeDollar = "BZD"
    case bermudianDollar = "BMD"
    case boliviano = "BOB"
    case bolívar = "VEF"
    case brazilianReal = "BRL"
    case bruneiDollar = "BND"
    case bulgarianLev = "BGN"
    case burundiFranc = "BIF"
    case caboVerdeEscudo = "CVE"
    case canadianDollar = "CAD"
    case caymanIslandsDollar = "KYD"
    case chileanPeso = "CLP"
    case colombianPeso = "COP"
    case comorianFranc  = "KMF"
    case congoleseFranc = "CDF"
    case convertibleMark = "BAM"
    case cordobaOro = "NIO"
    case costaRicanColon = "CRC"
    case cubanPeso = "CUP"
    case czechKoruna = "CZK"
    case dalasi = "GMD"
    case danishKrone = "DKK"
    case denar = "MKD"
    case djiboutiFranc = "DJF"
    case dobra = "STN"
    case dollar = "USD"
    case dominicanPeso = "DOP"
    case dong = "VND"
    case eastCaribbeanDollar = "XCD"
    case egyptianPound = "EGP"
    case elSalvadorColon = "SVC"
    case ethiopianBirr = "ETB"
    case euro = "EUR"
    case falklandIslandsPound = "FKP"
    case fijiDollar = "FJD"
    case forint = "HUF"
    case ghanaCedi = "GHS"
    case gibraltarPound = "GIP"
    case gourde = "HTG"
    case guarani = "PYG"
    case guineanFranc = "GNF"
    case guyanaDollar = "GYD"
    case hongKongDollar = "HKD"
    case hryvnia = "UAH"
    case icelandKrona = "ISK"
    case indianRupee = "INR"
    case iranianRial = "IRR"
    case iraqiDinar = "IQD"
    case jamaicanDollar = "JMD"
    case jordanianDinar = "JOD"
    case kenyanShilling = "KES"
    case kina = "PGK"
    case kuna = "HRK"
    case kuwaitiDinar = "KWD"
    case kwanza = "AOA"
    case kyat = "MMK"
    case laoKip = "LAK"
    case lari = "GEL"
    case lebanesePound = "LBP"
    case lempira = "HNL"
    case leone = "SLL"
    case liberianDollar = "LRD"
    case libyanDinar = "LYD"
    case lilangeni = "SZL"
    case loti = "LSL"
    case malagasyAriary = "MGA"
    case malawiKwacha = "MWK"
    case malaysianRinggit = "MYR"
    case mauritiusRupee = "MUR"
    case mexicanPeso = "MXN"
    case moldovanLeu = "MDL"
    case moroccanDirham = "MAD"
    case mozambiqueMetical = "MZN"
    case naira = "NGN"
    case nakfa = "ERN"
    case namibiaDollar = "NAD"
    case nepaleseRupee = "NPR"
    case netherlandsAntilleanGuilder = "ANG"
    case newIsraeliSheqel = "ILS"
    case newTaiwanDollar = "TWD"
    case newZealandDollar = "NZD"
    case ngultrum =  "BTN"
    case northKoreanWon = "KPW"
    case norwegianKrone = "NOK"
    case ouguiya = "MRU"
    case paanga = "TOP"
    case pakistanRupee = "PKR"
    case pataca = "MOP"
    case pesoUruguayo = "UYU"
    case philippinePiso = "PHP"
    case poundSterling = "GBP"
    case pula = "BWP"
    case qatariRial = "QAR"
    case quetzal = "GTQ"
    case rand = "ZAR"
    case rialOmani = "OMR"
    case riel = "KHR"
    case romanianLeu = "RON"
    case rufiyaa = "MVR"
    case rupiah = "IDR"
    case russianRuble = "RUB"
    case rwandaFranc = "RWF"
    case saintHelenaPound = "SHP"
    case saudiRiyal = "SAR"
    case serbianDinar = "RSD"
    case seychellesRupee = "SCR"
    case singaporeDollar = "SGD"
    case sol = "PEN"
    case solomonIslandsDollar = "SBD"
    case som = "KGS"
    case somaliShilling = "SOS"
    case somoni = "TJS"
    case southSudanesePound = "SSP"
    case sriLankaRupee = "LKR"
    case sudanesePound = "SDG"
    case surinamDollar = "SRD"
    case swedishKrona = "SEK"
    case swissFranc = "CHF"
    case syrianPound = "SYP"
    case taka = "BDT"
    case tala = "WST"
    case tanzanianShilling = "TZS"
    case tenge = "KZT"
    case trinidadAndTobagoDollar = "TTD"
    case tugrik = "MNT"
    case tunisianDinar = "TND"
    case turkishLira = "TRY"
    case turkmenistanNewManat = "TMT"
    case uaeDirham = "AED"
    case ugandaShilling = "UGX"
    case uzbekistanSum = "UZS"
    case vatu = "VUV"
    case won = "KRW"
    case yemeniRial = "YER"
    case yen = "JPY"
    case yuanRenminbi = "CNY"
    case zambianKwacha = "ZMW"
    case zimbabweDollar = "ZWL"
    case zloty = "PLN"
    
    var localized: String {
        switch self {
        case .albaniaLek: return "Albanian Lek"
        case .afghani: return "Afghanistan Afghani"
        case .algerianDinar: return "Algerian Dinar"
        case .argentinePeso: return "Argentina Peso"
        case .armenianDram: return "Armenian Dram"
        case .arubanFlorin: return "Aruban Florin"
        case .australianDollar: return "Australian Dollar"
        case .azerbaijanManat: return "Azerbaijan Manat"
        case .bahamianDollar: return "Bahamian Dollar"
        case .bahrainiDinar: return "Bahraini Dinar"
        case .baht: return "Thai Baht"
        case .balboa: return "Panamanian Balboa"
        case .barbadosDollar: return "Barbadian Dollar"
        case .belarusianRuble: return "Belarusian Ruble"
        case .belizeDollar: return "Belize Dollar"
        case .bermudianDollar: return "Bermudian Dollar"
        case .boliviano: return "Bolivian Boliviano"
        case .bolívar: return "Venezuelan Bolívar"
        case .brazilianReal: return "Brazilian Real"
        case .bruneiDollar: return "Brunei Dollar"
        case .bulgarianLev: return "Bulgarian Lev"
        case .burundiFranc: return "Burundi Franc"
        case .caboVerdeEscudo: return "Cabo Verdean Escudo"
        case .canadianDollar: return "Canadian Dollar"
        case .caymanIslandsDollar: return "Cayman Islands Dollar"
        case .chileanPeso: return "Chilean Peso"
        case .colombianPeso: return "Colombian Peso"
        case .comorianFranc: return "Comorian Franc"
        case .congoleseFranc: return "Congolese Franc"
        case .convertibleMark: return "Bosnia and Herzegovina Convertible Mark"
        case .cordobaOro: return "Nicaraguan Cordoba"
        case .costaRicanColon: return "Costa Rican Colon"
        case .cubanPeso: return "Cuban Peso"
        case .czechKoruna: return "Czech Koruna"
        case .dalasi: return "Gambian Dalasi"
        case .danishKrone: return "Danish Krone"
        case .denar: return "Macedonian Denar"
        case .djiboutiFranc: return "Djiboutian Franc"
        case .dobra: return "Sao Tome and Principe Dobra"
        case .dollar: return "US Dollar"
        case .dominicanPeso: return "Dominican Peso"
        case .dong: return "Vietnamese Dong"
        case .eastCaribbeanDollar: return "East Caribbean Dollar"
        case .egyptianPound: return "Egyptian Pound"
        case .elSalvadorColon: return "Salvadoran Colón"
        case .ethiopianBirr: return "Ethiopian Birr"
        case .euro: return "Euro"
        case .falklandIslandsPound: return "Falkland Islands Pound"
        case .fijiDollar: return "Fijian Dollar"
        case .forint: return "Hungarian Forint"
        case .ghanaCedi: return "Ghanaian Cedi"
        case .gibraltarPound: return "Gibraltar Pound"
        case .gourde: return "Haitian Gourde"
        case .guarani: return "Paraguayan Guarani"
        case .guineanFranc: return "    Guinean Franc"
        case .guyanaDollar: return "Guyanese Dollar"
        case .hongKongDollar: return "Hong Kong Dollar"
        case .hryvnia: return "Ukrainian Hryvnia"
        case .icelandKrona: return "    Icelandic Krona"
        case .indianRupee: return "Indian Rupee"
        case .iranianRial: return "Iranian Rial"
        case .iraqiDinar: return "Iraqi Dinar"
        case .jamaicanDollar: return "Jamaican Dollar"
        case .jordanianDinar: return "Jordanian Dinar"
        case .kenyanShilling: return "Kenyan Shilling"
        case .kina: return "Papua New Guinean Kina"
        case .kuna: return "Croatian Kuna"
        case .kuwaitiDinar: return "Kuwaiti Dinar"
        case .kwanza: return "Angolan Kwanza"
        case .kyat: return "Myanmar Kyat"
        case .laoKip: return "Lao Kip"
        case .lari: return "Georgian Lari"
        case .lebanesePound: return "    Lebanese Pound"
        case .lempira: return "Honduran Lempira"
        case .leone: return "Sierra Leonean Leone"
        case .liberianDollar: return "Liberian Dollar"
        case .libyanDinar: return "Libyan Dinar"
        case .lilangeni: return "Swazi Lilangeni"
        case .loti: return "Lesotho Loti"
        case .malagasyAriary: return "Malagasy Ariary"
        case .malawiKwacha: return "Malawian Kwacha"
        case .malaysianRinggit: return "Malaysian Ringgit"
        case .mauritiusRupee: return "Mauritian Rupee"
        case .mexicanPeso: return "Mexican Peso"
        case .moldovanLeu: return "Moldovan Leu"
        case .moroccanDirham: return "Moroccan Dirham"
        case .mozambiqueMetical: return "Mozambican Metical"
        case .naira: return "Nigerian Naira"
        case .nakfa: return "Eritrean Nakfa"
        case .namibiaDollar: return "Namibian Dollar"
        case .nepaleseRupee: return "Nepalese Rupee"
        case .netherlandsAntilleanGuilder: return "Netherlands Antillean Guilder"
        case .newIsraeliSheqel: return "Israeli New Shekel"
        case .newTaiwanDollar: return "New Taiwan Dollar"
        case .newZealandDollar: return "New Zealand Dollar"
        case .ngultrum: return "Bhutanese Ngultrum"
        case .northKoreanWon: return "North Korean Won"
        case .norwegianKrone: return "Norwegian Krone"
        case .ouguiya: return "Mauritanian Ouguiya"
        case .paanga: return "Tongan Pa’anga"
        case .pakistanRupee: return "Pakistani Rupee"
        case .pataca: return "Macanese Pataca"
        case .pesoUruguayo: return "Uruguayan Peso"
        case .philippinePiso: return "Philippine Peso"
        case .poundSterling: return "Pound sterling"
        case .pula: return "Botswana Pula"
        case .qatariRial: return "Qatari Riyal"
        case .quetzal: return "Guatemalan Quetzal"
        case .rand: return "South African Rand"
        case .rialOmani: return "Omani Rial"
        case .riel: return "Cambodian Riel"
        case .romanianLeu: return "Romanian Leu"
        case .rufiyaa: return "Maldivian Rufiyaa"
        case .rupiah: return "Indonesian Rupiah"
        case .russianRuble: return "Russian Ruble"
        case .rwandaFranc: return "Rwandan Franc"
        case .saintHelenaPound: return "Saint Helena Pound"
        case .saudiRiyal: return "Saudi Arabian Riyal"
        case .serbianDinar: return "Serbian Dinar"
        case .seychellesRupee: return "Seychellois Rupee"
        case .singaporeDollar: return "Singapore Dollar"
        case .sol: return "Peruvian Sol"
        case .solomonIslandsDollar: return "Solomon Islands Dollar"
        case .som: return "Kyrgyzstani Som"
        case .somaliShilling: return "Somali Shilling"
        case .somoni: return "Tajikistani Somoni"
        case .southSudanesePound: return "South Sudanese Pound"
        case .sriLankaRupee: return "Sri Lankan Rupee"
        case .sudanesePound: return "Sudanese Pound"
        case .surinamDollar: return "Surinamese Dollar"
        case .swedishKrona: return "Swedish Krona"
        case .swissFranc: return "Swiss Franc"
        case .syrianPound: return "Syrian Pound"
        case .taka: return "Bangladeshi Taka"
        case .tala: return "Samoan Tala"
        case .tanzanianShilling: return "Tanzanian Shilling"
        case .tenge: return "Kazakhstani Tenge"
        case .trinidadAndTobagoDollar: return "Trinidad and Tobago Dollar"
        case .tugrik: return "Mongolian Tugrik"
        case .tunisianDinar: return "Tunisian Dinar"
        case .turkishLira: return "Turkish Lira"
        case .turkmenistanNewManat: return "Turkmen Manat"
        case .uaeDirham: return "UAE Dirham"
        case .ugandaShilling: return "Ugandan Shilling"
        case .uzbekistanSum: return "Uzbekistani Sum"
        case .vatu: return "Vanuatu Vatu"
        case .won: return "South Korean Won"
        case .yemeniRial: return "Yemeni Rial"
        case .yen: return "Japanese Yen"
        case .yuanRenminbi: return "Chinese Yuan Renminbi"
        case .zambianKwacha: return "Zambian Kwacha"
        case .zimbabweDollar: return "Zimbabwean Dollar"
        case .zloty: return "Polish Zloty"
        }
    }
}
